// flow-typed signature: 01fd639d05cab1fc48e8fa119d716824
// flow-typed version: <<STUB>>/globby_v^6.1.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'globby'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'globby' {
  declare module.exports: (patterns: Array<string>) => Promise<Array<string>>
}
